# fly.toml app configuration file generated for phonebook-backend-return0 on 2023-11-19T02:43:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-backend-return0"
primary_region = "ams"

[build]

[env]
  PORT = "3000" # add this
  VITE_PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
